// Generated by diesel_ext

#![allow(unused)]
#![allow(clippy::all)]

use crate::*;
use diesel::{self, prelude::*};
use schema::cars;
use serde::{Deserialize, Serialize};

#[derive(Deserialize, Serialize, Queryable, Debug)]
pub struct Car {
    pub id: i32,
    pub name: String,
    pub model: String,
}

#[derive(Deserialize, Serialize, Insertable, Debug)]
#[table_name = "cars"]
pub struct NewCar {
    pub name: Option<String>,
    pub model: Option<String>,
}
