// Generated by diesel_ext

#![allow(unused)]
#![allow(clippy::all)]

use crate::*;
use diesel::{self, prelude::*};
use schema::cars;
use serde::{Deserialize, Serialize};
use validator::{Validate, ValidationError};

#[derive(Deserialize, Serialize, Queryable, Debug)]
pub struct Car {
    pub id: i32,
    pub name: String,
    pub model: String,
}

#[derive(Deserialize, Serialize, Insertable, Validate, Debug)]
#[table_name = "cars"]
pub struct NewCar {
    #[validate(required,length(min = 1, max = 100))]
    pub name: Option<String>,
    #[validate(required,length(min = 1, max = 100))]
    pub model: Option<String>,
}
